server:
  port: 8080

spring:
  profiles:
    active: ${APP_PROFILE:local}

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/monitor_service_db
    username: tcc_user
    password: tcc_password
    hikari:
      minimum-idle: 10
      maximum-pool-size: 1000
  sql:
    init:
      mode: always
  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true

  flyway:
    locations: /db/commons, /db/local
    clean-disabled: false

springdoc:
  swagger-ui:
    path: /swagger

monitor-service:
  name: MONITOR-SERVICE

auth-service:
  url: ${AUTH_SERVICE:http://localhost:8085}